let locale='pt-BR',selectedAtlas='pt',selectedInterest='language',activeCase=null,lastFocused=null;
const initialLetters=['ㄱ','ㄲ','ㄴ','ㄷ','ㄸ','ㄹ','ㅁ','ㅂ','ㅃ','ㅅ','ㅆ','ㅇ','ㅈ','ㅉ','ㅊ','ㅋ','ㅌ','ㅍ','ㅎ'];
const vowelLetters=['ㅏ','ㅐ','ㅑ','ㅒ','ㅓ','ㅔ','ㅕ','ㅖ','ㅗ','ㅘ','ㅙ','ㅚ','ㅛ','ㅜ','ㅝ','ㅞ','ㅟ','ㅠ','ㅡ','ㅢ','ㅣ'];
const readings={ㅎ:'h',ㄱ:'g',ㄴ:'n',ㅁ:'m',ㅏ:'a',ㅗ:'o',ㅜ:'u',ㅣ:'i'};let initial='ㅎ',vowel='ㅏ';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],index=()=>LOCALE_ORDER.indexOf(locale),t=key=>COPY[locale][key];
const escapeText=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderEducation(){const n=index();$('#education-highlights').innerHTML=EDUCATION.filter(e=>e.featured).map(e=>`<article><small>${escapeText(e.date)}</small><h3>${escapeText(e.titles[n])}</h3><p>${escapeText(e.place)}</p><p>${escapeText(e.notes?.[n]||'')}</p></article>`).join('');$('#education-archive').innerHTML=['formal','programs','certificates'].map(group=>`<div class="archive-group"><h3>${escapeText(t(group))}</h3>${EDUCATION.filter(e=>e.group===group).map(e=>`<div class="archive-entry"><strong>${escapeText(e.titles[n])}</strong><span>${escapeText(e.place)}${e.notes?'<br>'+escapeText(e.notes[n]):''}</span><time>${escapeText(e.date)}</time></div>`).join('')}</div>`).join('')}
function renderAtlas(){const a=ATLAS[selectedAtlas];$('#atlas-type').textContent=t(a.type);$('#atlas-word').textContent=a.word;$('#atlas-description').textContent=a.copy[index()]}
function renderInterest(){$('#interest-copy').textContent=t({language:'languageCopy',data:'dataCopy',ai:'aiCopy'}[selectedInterest])}
function renderCase(){if(!activeCase)return;if(activeCase==='research'){renderResearch();return;}const c=CASES[activeCase],n=index();$('#case-status').textContent=t(c.status);$('#case-content').innerHTML=`<div class="case-header"><h2 id="case-title">${escapeText(c.title)}</h2><p>${escapeText(c.intro[n])}</p></div><div class="case-grid">${['problem','contribution','results'].map(key=>`<section class="case-section"><h3>${escapeText(t(key))}</h3><p>${escapeText(c[key][n])}</p></section>`).join('')}<section class="case-section"><h3>${escapeText(t('tools'))}</h3><p>${escapeText(c.tools)}</p></section></div>${c.metrics?`<div class="case-metrics">${c.metrics.map(([value,key])=>`<div><strong>${escapeText(value)}</strong><span>${escapeText(({calibration:['textos na calibração interna','internal calibration texts','textos de calibración interna','내부 보정용 텍스트'],reviews:['resenhas','reviews','reseñas','영화 리뷰'],conflicts:['conflitos de rótulo','label conflicts','etiquetas contradictorias','라벨 충돌']}[key]||['KRDICT','KRDICT','KRDICT','KRDICT'])[n])}</span></div>`).join('')}</div>`:''}${c.note?`<p class="case-note">${escapeText(c.note[n])}</p>`:''}<div class="case-links">${c.links.map(([label,href])=>`<a href="${href}" target="_blank" rel="noopener">${label==='Video'?['Vídeo','Video','Vídeo','영상'][n]:label} ＋</a>`).join('')}</div>`}
function setLanguage(value){if(!COPY[value])value='pt-BR';locale=value;document.documentElement.lang=value;$('#language').value=value;$$('[data-t]').forEach(el=>el.textContent=t(el.dataset.t));$$('[data-alt]').forEach(el=>el.setAttribute('alt',t(el.dataset.alt)));renderEducation();renderAtlas();renderInterest();renderCase();if(typeof refreshPuzzleLabels==='function')refreshPuzzleLabels();$('#close-case').setAttribute('aria-label',t('close'));updateMotionButton();document.title=['Lívia Aguiar · Linguagem, Dados & IA','Lívia Aguiar · Language, Data & AI','Lívia Aguiar · Lenguas, Datos e IA','리비아 아기아르 · 언어, 데이터, AI'][index()];document.querySelector('meta[name=description]').content=t('heroIntro');try{localStorage.setItem('livia-language',value)}catch{}const url=new URL(location.href);url.searchParams.set('lang',value);history.replaceState(null,'',url)}
$('#language').addEventListener('change',e=>setLanguage(e.target.value));
$$('[data-language-node]').forEach(button=>button.addEventListener('click',()=>{selectedAtlas=button.dataset.languageNode;$$('[data-language-node]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button))});renderAtlas()}));
$$('[data-interest]').forEach(button=>{button.setAttribute('aria-pressed',String(button.classList.contains('active')));button.addEventListener('click',()=>{selectedInterest=button.dataset.interest;$$('[data-interest]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button))});renderInterest()})});
function composeSyllable(first,second){const i=initialLetters.indexOf(first),v=vowelLetters.indexOf(second);if(i<0||v<0)throw new Error('Invalid Hangul letters');return String.fromCharCode(0xAC00+(i*21+v)*28)}
const dialog=$('#case-dialog');$$('[data-project]').forEach(button=>button.addEventListener('click',()=>{lastFocused=button;activeCase=button.dataset.project;renderCase();dialog.showModal();document.body.classList.add('modal-open');$('#close-case').focus()}));$('#close-case').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()});dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');lastFocused?.focus();activeCase=null});
const reduced=matchMedia('(prefers-reduced-motion: reduce)'),finePointer=matchMedia('(pointer: fine)');let motionOff=reduced.matches;try{motionOff=localStorage.getItem('livia-motion')==='off'||reduced.matches}catch{}
function updateMotionButton(){document.body.classList.toggle('motion-off',motionOff);$('#motion-toggle').textContent=motionOff?'▷':'Ⅱ';$('#motion-toggle').setAttribute('aria-label',t(motionOff?'resume':'pause'));$('#motion-toggle').setAttribute('aria-pressed',String(motionOff))}
$('#motion-toggle').addEventListener('click',()=>{motionOff=!motionOff;updateMotionButton();try{localStorage.setItem('livia-motion',motionOff?'off':'on')}catch{}updateScroll()});reduced.addEventListener('change',e=>{if(e.matches){motionOff=true;updateMotionButton();updateScroll()}});
let scheduled=false;function updateScroll(){scheduled=false;const total=document.documentElement.scrollHeight-innerHeight;const p=total>0?scrollY/total:0;$('#read-progress').style.width=p*100+'%';if(motionOff){setOpeningScene(0);document.documentElement.style.setProperty('--hero-progress','0');return}const opening=$('.opening');const travel=opening.offsetHeight-innerHeight;const hp=Math.max(0,Math.min(1,scrollY/Math.max(1,travel)));document.documentElement.style.setProperty('--hero-progress',hp.toFixed(3));setOpeningScene(hp);document.documentElement.style.setProperty('--graph-angle',(scrollY*.07)+'deg');document.documentElement.style.setProperty('--dash-offset',(-scrollY*.08).toFixed(1));const guide=$('.journey-guide');guide.style.bottom=(28+p*Math.min(260,innerHeight*.3))+'px'}
window.addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(updateScroll)}},{passive:true});window.addEventListener('resize',updateScroll);
window.addEventListener('pointermove',e=>{if(motionOff||!finePointer.matches)return;const x=(e.clientX/innerWidth-.5),y=(e.clientY/innerHeight-.5);const aura=$('.cursor-aura');aura.style.left=e.clientX+'px';aura.style.top=e.clientY+'px';aura.style.opacity='1';$$('.parallax').forEach(el=>{const d=Number(el.dataset.depth);el.style.setProperty('--px',x*d+'px');el.style.setProperty('--py',y*d+'px')})},{passive:true});document.addEventListener('pointerleave',()=>$('.cursor-aura').style.opacity='0');
$$('.tilt').forEach(el=>{el.addEventListener('pointermove',e=>{if(motionOff||!finePointer.matches)return;const r=el.getBoundingClientRect();el.style.setProperty('--tilt-y',((e.clientX-r.left)/r.width-.5)*18+'deg');el.style.setProperty('--tilt-x',-((e.clientY-r.top)/r.height-.5)*12+'deg')});el.addEventListener('pointerleave',()=>{el.style.removeProperty('--tilt-x');el.style.removeProperty('--tilt-y')})});
const pixels=$('.data-pixels');for(let i=0;i<100;i++){const dot=document.createElement('i');dot.style.setProperty('--alpha',(.15+(i*17%83)/100).toFixed(2));pixels.append(dot)}
if('IntersectionObserver'in window){const reveal=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');reveal.unobserve(entry.target)}})},{threshold:.1});$$('.section-title,.featured-project,.project-small,.about-layout,.education-highlights,.research-note,.lab-layout').forEach(el=>{el.classList.add('reveal');reveal.observe(el)});const chapters=new IntersectionObserver(entries=>{for(const e of entries){if(e.isIntersecting){$$('.journey-nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id))}}},{rootMargin:'-20% 0px -55% 0px'});$$('main>section[id]').forEach(el=>chapters.observe(el))}
let saved;try{saved=localStorage.getItem('livia-language')}catch{}setLanguage(new URL(location.href).searchParams.get('lang')||saved||'pt-BR');updateScroll();
$$('.word-stream button').forEach(button=>button.addEventListener('click',()=>{const stream=$('.word-stream');stream.prepend(button);button.focus()}));

function setOpeningScene(progress){const small=innerWidth<=700;const smooth=(a,b,x)=>{const v=Math.max(0,Math.min(1,(x-a)/(b-a)));return v*v*(3-2*v)};const copy=small?1:1-smooth(.08,.48,progress);const art=small?1:1-.82*smooth(.15,.6,progress);const caption=small?1:smooth(.52,.84,progress);const style=document.documentElement.style;style.setProperty('--scene-copy-opacity',copy.toFixed(3));style.setProperty('--scene-art-opacity',art.toFixed(3));style.setProperty('--scene-caption-opacity',caption.toFixed(3));style.setProperty('--scene-caption-y',(24*(1-caption)).toFixed(1)+'px')}

function renderResearch(){const n=index();$('#case-status').textContent=t('researchLabel');$('#case-content').innerHTML=`<div class="case-header research-header"><h2 id="case-title">${escapeText(t('thesisTitle'))}</h2></div><section class="research-abstract"><h3>${escapeText(t('abstractLabel'))}</h3>${RESEARCH_DETAIL.abstracts[n].split('\n\n').map(p=>`<p>${escapeText(p)}</p>`).join('')}</section><section class="research-keywords"><h3>${escapeText(t('keywordsLabel'))}</h3><div>${RESEARCH_DETAIL.keywords[n].map(word=>`<span>${escapeText(word)}</span>`).join('')}</div></section><section class="research-citation"><h3>${escapeText(t('citationLabel'))}</h3><p>${escapeText(t('comingSoon'))}</p></section><div class="case-links"><button class="repository-soon" disabled>${escapeText(t('repositoryLabel'))} · ${escapeText(t('comingSoon'))}</button></div>`;}
